name: ESLint Code Formatter
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        run: |
            cd Code/frontend
            npm install babel-eslint eslint eslint-plugin-react
            npx eslint .
